# we recommend to read config_details.yaml first.
data:
  data_path: './downloaded_data/ss_overfit'
  valid_path: 'debug/valid'
  num_workers: 32
  noise_sort: 'ot'
  use_rot_aug: False  # <---- whether to use rotation augmentation when training
  use_scale_aug: False  # <---- whether to use scaling augmentation when training
  use_permute_aug: True  # <---- whether to use permutation augmentation when training

# recommend to use default settings
model:
  model_type: "equidit"
  use_rmsnorm: true
  # in_chans: 32

  hidden_dim: 768
  num_heads: 12
  max_length: 800
  num_layers: 12
  gradient_checkpointing: False
  use_coord_encoding: True
  version: 3
  pe_freq: 20
  mixed_precision:
  use_dit_like_pe: False
  face_cond: True
  face_bin: 20

# recommend to use default settings
train:
  max_steps: 100000 # 100k is enough for overfitting
  global_batch_size: 128
  output_dir: 'output'
  exp_name: 'overfit-base-120m-ot-x1' # <---- experiment name, set as you like
  log_every: 1
  ckpt_every: 5000 # 5000 
  
optimizer:
  lr: 0.0001
  beta2: 0.95
  
# recommend to use default settings
transport:
  path_type: Linear
  prediction: velocity
  use_lognorm: true
  use_jit: true

# recommend to use default settings
sample:
  mode: ODE
  sampling_method: euler
  atol: 0.000001
  rtol: 0.0005
  reverse: false
  num_sampling_steps: 50
  cfg_scale: 1.0 
  
  # recommend to use default settings
  per_proc_batch_size: 4
  timestep_shift: 0
