# we recommend to read config_details.yaml first.


ckpt_path: 'path/to/your/checkpoint.pt' # <---- download our pre-trained lightningdit or your own checkpoint

data:
  valid_path: 'debug/valid'
  data_path: './downloaded_data/objaverse'
  fid_reference_file: 'path/to/your/VIRTUAL_imagenet256_labeled.npz' # <---- path to your fid_reference_file.npz. download it from ADM

  # recommend to use default settings
  image_size: 256
  num_classes: 1000
  num_workers: 8
  latent_norm: true
  latent_multiplier: 1.0

  do_dataset_normalize: True
  noise_sort: 'ot'
  num_bins: 256  # <---- number of bins for classification decoder, set to 256

# recommend to use default settings
model:
  model_type: "equidit"
  use_qknorm: false
  use_swiglu: true
  use_rope: true
  use_rmsnorm: true
  wo_shift: false
  latent_channels: 3

  hidden_dim: 768
  num_heads: 12
  max_length: 800
  input_dim: 9
  num_layers: 12
  gradient_checkpointing: False
  use_coord_encoding: True
  version: 3
  pe_freq: 20
  mixed_precision:
  use_dit_like_pe: False
  face_cond: True
  face_bin: 10
  decoder_type: "cls"


# recommend to use default settings
train:
  max_steps: 400000
  global_batch_size: 256 #64 per gpu
  global_seed: 0
  output_dir: 'output'
  exp_name: 'vae_cls' # <---- experiment name, set as you like
  ckpt: null
  log_every: 100
  ckpt_every: 5000 # 100 for debug
  kl_weight: 0.0001 # <---- kl weight, 1e-4?
  
optimizer:
  lr: 0.0002
  beta2: 0.95
