# we recommend to read config_details.yaml first.


ckpt_path: 'path/to/your/checkpoint.pt' # <---- download our pre-trained lightningdit or your own checkpoint

data:
  valid_path: 'debug/valid'
  data_path: 'downloaded_data/shapenet-03636649' # 'downloaded_data/objaverse'

  # recommend to use default settings
  num_workers: 8
  latent_norm: true
  latent_multiplier: 1.0

  do_dataset_normalize: false
  noise_sort: 'ot'
  max_length: 800

  num_bins: 8192  # quantize final results
  use_rot_aug: True  # <---- whether to use rotation augmentation when training
  use_scale_aug: True  # <---- whether to use scaling augmentation when training
  use_repa: False
  use_permut_aug: False
  use_decimated_dataset: True
# recommend to use default settings
model:
  model_type: "equivae"
  use_qknorm: false
  use_swiglu: true
  use_rope: true
  use_rmsnorm: true
  wo_shift: false
  latent_channels: 3

  # in_chans: 32

  hidden_dim: 768
  num_heads: 12
  max_length: 800
  input_dim: 9
  num_layers: 12
  gradient_checkpointing: False
  use_coord_encoding_decoder: True
  version: 3
  pe_freq: 20
  mixed_precision:
  use_dit_like_pe: False
  face_cond: True
  face_bin: 10
  decoder_type: "reg"
  use_rms: True
  noise_std: 0.01
  loss_type: "mse"
  huber_delta: 0.1
  use_equi_model: True
  

# recommend to use default settings
train:
  max_steps: 50000 # 50k
  global_batch_size: 64 #768
  global_seed: 0
  output_dir: 'output'
  exp_name: 'decoder_001_noise_eq' # <---- experiment name, set as you like
  ckpt: null
  log_every: 100
  ckpt_every: 3000 # 100 for debug
  kl_weight: 0.001 # <---- 1e-3
  resume: false
  
optimizer:
  lr: 0.0001 # 1e-4
  beta2: 0.95